site_name: LMA

theme:
  name: "material"
  features:
    - navigation.sections

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - 'General':
    - Installation: installation.md
    - Reference: reference.md
  - 'Gallery':
    - Tutorial 1 - Rat retina: rat_retina.ipynb
    - Tutorial 2 - Zebrafish retina: zebrafish_retina.ipynb
    - Tutorial 3 - Mouse blastocyst: mouse_blastocyst.ipynb

plugins:
  - mkdocs-jupyter
  - mkdocstrings

markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences